internal/lexer/lexer.go
The existing comment mentioned to EOF/ EOL but the wrong check method was used.
Fixes #1
=> Allows EOF at end of last command script line

README.md, internal/config/config.go, internal/runfile/command.go, main.go
Short-circuits option parsing when no options defined, passing all args to command script.
This implies that `-h|--help` is only supported when the command explicitly defines one or more options.
Fixes #3 
---
TODO Before Merging:
* ~~Update the README for this change.~~
=> Passes all args to script if no options defined

README.md, internal/lexer/lexer.go, internal/lexer/runes.go, internal/lexer/tokens.go, internal/parser/parser.go
This change enables command names to contain dash `'-'` characters, after the first character.
Docs are updated to reflect the change and also clarify a few other aspects of command naming.
Fixes #7
=> Adds support for '-' in command names

README.md, internal/runfile/runfile.go
This change adds he ability to auto-detect `#!` scripts (as opposed to needing to explicitly specify `'#!'` as the shell)
Specifying `'#!'` explicitly still works, but has been removed from the documentation.
Fixes #10
=> Adds auto-detection for "#!" scripts

internal/ast/ast.go
I was adding the attributes to the commands variable scope too late in the process.
Moved the step to happen to happen before the export statements are evaluated.
---
Fixes #14
=> Makes attributes available to command exports

internal/ast/ast.go
Adds .SHELL to available attributes before processing the parsed Runfile.
---
Fixes #16
=> Makes .SHELL available for read

README.md, main.go
Instead of just hiding the `version` command in shebang mode, I decided to rename it.
In regular mode, the command will still be available as `version`:
```
$ run -r my-runfile version
run v0.0.0
```
But it shebang mode, the command I will be available under `run-version`:
```
$ ./my-runfile-app run-version
run v0.0.0
```
This leaves your Runfile free to define its own `version` command
__Runfile__
```
version:
echo "my-runfile-app v1.2.3"
```
__output__
```
$ ./my-runfile-app version
my-runfile-app v1.2.3
$ ./my-runfile-app run-version
run v0.0.0
```
---
Fixes #18
=> Renames version as run-version in shebang mode

README.md, internal/ast/ast.go, internal/config/config.go, main.go
Adds `.RUN` and `.RUNFILE` attributes to make it possible to invoke other commands / runfiles from within your command script.
_Runfile_
```
##
test:
"${RUN}" -r "${RUNFILE}" hello
hello:
echo "Hello, World"
```
_output_
```
$ run test
Hello, World
```
---
Fixes #20
=> Adds .RUN and .RUNFILE attributes

PKGBUILD, deployments/aur/PKGBUILD
This would be a first step for making binary packages generally available (although in this current state you'd push just the `PKGBUILD` and its corresponding `.SRCINFO` to the Archlinux [aur](https://aur.archlinux.org) and people would download the `PKGBUILD` and build it), you can use `makepkg` (on arch) to build a `.pkg.tar.xz` that would go with a release.
=> Add a Archlinux PKGBUILD

internal/config/config.go, internal/runfile/command.go, main.go
This allows failing a command if a run script fails, for example.
=> run: Plumb the exit code of a command back to run

internal/exec/exec.go, main.go
ioutil.TempDir passes the responsibility of cleanup onto us. We weren't
doing this, which leads to a temp dir that is full of runfile- temp
entries.
Thus, introduce a way to cleanup after ourselves.
This isn't exactly a problem, as most modern distributions
automatically clear stale entries out of /tmp, but it looks rather messy.
=> exec: Provide a way to cleanup the temporary dir

internal/ast/ast.go, internal/parser/parser.go, internal/runfile/runfile.go, main.go
Usecase:
```
foo:
echo "hello"
foo:
echo "world"
```
Gives: `run: Duplicate command: foo defined on line 4 -- originally defined on line 0`
```
version:
echo "hello"
```
Gives: `run: Duplicate command: version defined on line 0 -- this command is built-in`
Marked as  WIP because the first line is showing up with line 0. I'm not sure if this is a bug in the parser/tokenizer, or if I'm missing something. It seems strange that the second definition is correctly showing up as line 4...
=> WIP: Show a better error on duplicate command

.goreleaser.yml, README.md, go.mod, go.sum, internal/ast/ast.go, internal/config/config.go, internal/lexer/lexer.go, internal/lexer/runes.go, internal/lexer/tokens.go, internal/parser/parser.go, internal/runfile/command.go, internal/runfile/scope.go, internal/util/util.go, main.go
Imports [goreleaser/fileglob](https://github.com/goreleaser/fileglob) for globbing support
Adds util.ReadFileIfExists helper method
Closes #44 
---
cc: @nikolay , @charandas
=> Adds support for INCLUDE directive

README.md, internal/ast/ast.go, internal/config/config.go, internal/parser/parser.go, internal/runfile/runfile.go, main.go
- Allows overriding commands as long as they are defined in *different* Runfiles
- Still can't define a command multiple times in *same* Runfile
- Command's list position based on first occurrence
- Command's display name based on first occurrence
bug: Display Runfile in post-parsing error reporting
chore: Capture Runfile in ast.Cmd and runfile.RunCmd
chore: Add builtin flag to config.Command
--- 
cc: @MadBomber Care to give this a test drive / once-over ?
=> feat: Add support for overriding commands

README.md, internal/ast/ast.go, internal/config/config.go, internal/parser/parser.go, main.go
Adds new attributes:
- .RUNFILE.DIR
- .SELF
- .SELF.DIR
chore: Adds config properties:
- config.RunfileAbsDir
- config.CurrentRunfile
- config.CurrentRunfileAbs
- config.CurrentRunfileAbsDir
bug: Fixes defer in for loop
TODO:
---
Fixes #52 
cc: @rburchell , @nikolay : Wanna give this a try and see how the chosen attributes feel in use?
=> feat: Add .RUNFILE.DIR, .SELF, .SELF.DIR

internal/lexer/lexer.go, internal/lexer/tokens.go, internal/parser/parser.go
chore: Makes LexDocBlockNQString public
chore: Replaces TokenConfigDescLine => TokenConfigDescLineStart
---
Fixes #53
=> bug: Allow Dynamic Content in Simple Titles

README.md, internal/ast/ast.go, internal/lexer/lexer.go, internal/lexer/tokens.go, internal/parser/parser.go, internal/runfile/command.go, internal/runfile/scope.go
Enables two quick ways to export an attribute:
Export with implied variable name based on attribute name
- EXPORT .ATTRIBUTE.NAME
- Implicitly assigns to variable ATTRIBUTE_NAME, ie
- Removes leading '.'
- Replaces remaining '.' characters with '_'
Export with explicit variable name
- EXPORT .ATTRIBUTE.NAME AS VAR_NAME
- Assigns to variable VAR_NAME
bug: Normalize attribute names in RHS references
TODO:
---
Fixes #57
=> feat: Easily export attributes

README.md, internal/ast/ast.go, internal/lexer/lexer.go, internal/lexer/runes.go, internal/lexer/tokens.go, internal/parser/parser.go, internal/runfile/command.go, internal/runfile/runfile.go
feat: Adds support for Required options
OPTION NAME ! ...
feat: Adds required indicator on option help screen
-s, --long <value> (required)
feat: Adds error messaging when required options not provided
feat: Adds support for Default option values
OPTION NAME ?= DEFAULT ...
feat: Adds default indicator on option help screen
-s, --long <value> (default: DEFAULT)
feat: For boolean options, a default value ALWAYS implies 'true'
- Will show configured default in help text
OPTION BOOL ?= enabled -b, --bool 
-b, --bool (default: enabled)
- Variable will be set to TRUE ("1") unless set to false via CLI
--bool=false | f | 0
feat: Adds support for explicitly marking option as Optional
OPTION NAME ? ...
- Added mostly to offer parity to '!'
chore: Renames config option Value to Example
chore: …
=> feat: Support required options; Support default option values

README.md, internal/ast/ast.go, internal/config/config.go, internal/lexer/lexer.go, internal/lexer/runes.go, internal/lexer/tokens.go, internal/parser/parser.go, internal/runfile/command.go, internal/runfile/runfile.go, internal/util/util.go, main.go
Adds Support for the following cmd options:
* RUN
* RUN.BEFORE
* RUN.AFTER
RUN is the same as RUN.BEFORE, running *before* your command is executed.
- Your command only runs if all before commands return exit code zero (0)
RUN.AFTER, as expected, runs *after* your command has finished executing
- After commands only run if your command returns exit code zero (0)
Execution halts if any RUN returns a non-zero exit code
Your command's environment variables are exported to the invoked command
usage:
Any standard variable assignment values can be used as arguments
- quoted strings, variable references, etc
chore: Runfile now stores []CmdProvider instead of []*RunCmd
- Can re-generate RunCmd in different env contexts
chore: Adds new meta token TokenNotNewline
- Generally indicates …
=> feat: Allow commands to RUN other commands

README.md, internal/ast/ast.go, internal/config/config.go, internal/lexer/lexer.go, internal/lexer/runereader.go, internal/lexer/runes.go, internal/lexer/tokens.go, internal/parser/parser.go, internal/runfile/command.go, internal/runfile/runfile.go, main.go
You can mark a command as hidden with '.':
.hidden:
echo "This command is hidden"
* Can be invoked by command config RUN actions
* RUN actions do not need to use '.'
* Will not show in CLI list of available commands
* Can still be invoked via CLI using '.name'
You can mark a command as private with '!':
!private:
echo "This command is private"
* Can only be invoked by command config RUN actions
* RUN actions do not need to use '!'
* Will not show in CLI list of available commands
* Cannot be invoked from CLI
---
TODO
=> feat: Add support for Hidden and Private Commands

README.md, main.go
Modifies RUNFILE_ROOTS logic to use user-specified Runfile pattern, when provided, or default to `Runfile`
bug: No-longer prints cmd not found error when Runfile could not be loaded.
---
Fixes #67 
cc: @xkcd386at care to take this for a spin and let me know how it goes?
=> feat: Use $RUNFILE in $RUNFILE_ROOTS logic

main.go
Updates the standard "Learn more" message to mention that example runfiles are available at the project homepage
---
Closes #80 
cc: @Gys
=> doc: Mention example runfiles available in link to homepage
